<?php
declare(strict_types=1);

namespace App\Controller;

use Cake\Database\Exception\DatabaseException;
use Cake\Datasource\Exception\RecordNotFoundException;
use Cake\Event\EventInterface;
use Cake\Http\Response;
use Cake\I18n\Date;
use Cake\I18n\DateTime;
use Cake\ORM\Exception\PersistenceFailedException;
use Exception;

class ManutencaosController extends AppController
{
    protected \Cake\Database\Connection $conexao;

   public function initialize(): void
   {
       parent::initialize(); // TODO: Change the autogenerated stub
       $this->conexao = $this->Manutencaos->getConnection();
   }

    public function index(): Response
    {
        if (!$this->request->is('post')) {
            return $this->gerarResposta(400, 'Requisição não suportada.');
        }

        $dados = $this->request->getData();

        $dataInicial = null;
        $dataFinal = null;

        if (!empty($dados['data_inicial'])) {
            $dataInicial = $dados['data_inicial'];
        }

        if (!empty($dados['data_final'])) {
            $dataFinal = $dados['data_inicial'];
        }

        try {
            $manutencaos = $this->fetchTable('Manutencaos');
            $query = $manutencaos
                ->find()
                ->select([
                    'cnpj_fornecedor' => 'Fornecedors.cnpj',
                    'nome_fornecedor' => 'Fornecedors.nome',
                    'telefone_fornecedor' => 'Fornecedors.telefone',
                    'modelo_veiculo' => 'Veiculos.modelo',
                    'placa_veiculo' => 'Veiculos.placa',
                    'nome_abreviado_fabricante' => 'Fabricantes.abreviado',
                    'nota_fiscal' => 'Manutencaos.notaFiscal',
                    'valor_manutencao' => 'Manutencaos.valor',
                    'data_manutencao' => 'Manutencaos.data',
                ])
                ->join([
                    'table' => 'Fornecedors',
                    'type' => 'INNER',
                    'conditions' => 'Fornecedors.id = Manutencaos.fornecedor_id',
                ])
                ->join([
                    'table' => 'Veiculos',
                    'type' => 'INNER',
                    'conditions' => 'Veiculos.id = Manutencaos.veiculo_id',
                ])
                ->join([
                    'table' => 'Fabricantes',
                    'type' => 'INNER',
                    'conditions' => 'Fabricantes.id = Veiculos.fabricante_id',
                ]);

            if ($dataInicial) {
                $query = $query->where(['data >= ' => new Date($dataInicial)], ['data' => 'date']);
            }

            if ($dataFinal) {
                $query = $query->where(['data <= ' => new Date($dataFinal)], ['data' => 'date']);
            }

            return $this->gerarResposta(200, [
                $this->chaveMensagem => 'Manutenções listadas com sucesso.',
                $this->chaveRetorno => $query->toArray(),
            ]);
        }
        catch (Exception $e) {
            return $this->gerarResposta(400, $e->getMessage());
        }
    }

    public function view(): Response
    {
        $msgNaoEncontrado = '';

        try {
            $dados = $this->request->getData();

            if (empty($dados)) {
                return $this->gerarResposta(400, 'Dados ausentes.');
            }

            $id = $this->request->getData('id');

            if (!$id) {
                return $this->gerarResposta(400, 'Informe o código da manutenção para buscá-la.');
            }

            $msgNaoEncontrado = 'Manutenção de código ' . $id . ' não encontrada.';
            $manutencao = $this->Manutencaos->get($id, contain: [
                'ManuPecas.Pecas'
            ]);

            return $this->gerarResposta(200, [
                $this->chaveRetorno => $manutencao,
                $this->chaveMensagem => 'Manutenção encontrada.',
            ]);
        }
        catch (RecordNotFoundException $e) {
            return $this->gerarResposta(400, [
                $this->chaveMensagem => $msgNaoEncontrado,
            ]);
        }
        catch (Exception $e) {
            return $this->gerarResposta(400, [
                $this->chaveMensagem => $e->getMessage(),
            ]);
        }
    }

    public function add(): Response
    {
        if (!$this->request->is('post')) {
            return $this->gerarResposta(400, 'Requisição inválida.');
        }

        $dados = $this->request->getData();

        if (empty($dados)) {
            return $this->gerarResposta(400, 'Informe a manutenção a ser lançada.');
        }

        $manuPecas = $dados["manu_pecas"];

        if (empty($manuPecas)) {
            return $this->gerarResposta(400, 'Deve haver ao menos uma peça vinculada à manutenção.');
        }

        try {
            $manutencao = $this->Manutencaos->newEmptyEntity();
            $manutencao = $this->Manutencaos->patchEntity($manutencao, $dados, [
                'associated' => ['ManuPecas']
            ]);

            $manutencao = $this->Manutencaos->saveOrFail($manutencao);
            return $this->gerarResposta(200, [
                'id' => $manutencao["id"],
                $this->chaveMensagem => 'Manutenção lançada com sucesso.',
            ]);
        }
        catch (PersistenceFailedException $e) {
            return $this->gerarResposta(400, [
                $this->chaveErros => $e->getAttributes(),
            ]);
        }
        catch (Exception $e) {
            return $this->gerarResposta(400, [
                $this->chaveMensagem => $e->getMessage()
            ]);
        }
    }

    public function edit(): Response
    {
        if (!$this->request->is('post')) {
            return $this->gerarResposta(400, 'Requisição inválida.');
        }

        $dados = $this->request->getData();

        if (empty($dados)) {
            return $this->gerarResposta(400, 'Informe a manutenção a ser corrigida.');
        }

        if (empty($dados['id'])) {
            return $this->gerarResposta(400, 'Informe o código da manutenção a ser corrigida.');
        }

        if (empty($dados['manu_pecas'])) {
            return $this->gerarResposta(400, 'Deve haver ao menos uma peça vinculada à manutenção.');
        }

        $id = $dados['id'];
        $manuPecas = $dados['manu_pecas'];

        $mensagemNaoEncontrado = '';
        $this->conexao->begin();

        try {
            $mensagemNaoEncontrado = 'Não existe uma manutenção com o código '
                . $id . ' para ser corrigida.';
            $manutencao = $this->Manutencaos->get($id, contain: ['ManuPecas']);

            $idsManuPecas = array_filter(array_column($manuPecas, 'id'));

            foreach ($manutencao->get("manu_pecas") as $manuPeca) {
                $vinculoIncluso = in_array($manuPeca["id"], $idsManuPecas);

                if (!$vinculoIncluso) {
                    $this->Manupecas->delete($manuPeca);
                }
            }

            $manutencao = $this->Manutencaos->patchEntity($manutencao, $dados, [
               'associated' => ['ManuPecas']
            ]);

            $this->Manutencaos->saveOrFail($manutencao);
            $this->conexao->commit();

            return $this->gerarResposta(200, [
                $this->chaveMensagem => 'Manutenção corrigida com sucesso.'
            ]);
        }
        catch (RecordNotFoundException) {
            $this->conexao->rollback();
            return $this->gerarResposta(400, [
                $this->chaveMensagem => $mensagemNaoEncontrado
            ]);
        }
        catch (PersistenceFailedException $e) {
            $this->conexao->rollback();
            return $this->gerarResposta(400, [
                $this->chaveErros => $e->getAttributes()
            ]);
        }
        catch (Exception $e) {
            $this->conexao->rollback();
            return $this->gerarResposta(400, [
                $this->chaveMensagem => $e->getMessage()
            ]);
        }
    }

    public function delete(): Response
    {
        if (!$this->request->is('post')) {
            return $this->gerarResposta(400, [
                $this->chaveMensagem => 'Tipo de requisição inválido.',
            ]);
        }

        $id = $this->request->getData('id');

        if (!$id) {
            return $this->gerarResposta(400, [
                $this->chaveMensagem => 'Informe o código da manutenção a ser excluída.',
            ]);
        }

        $mensagemNaoEncontrada = 'Não existe uma manutenção com o código ' . $id . ' para ser excluída.';

        try {
            $manutencao = $this->Manutencaos->get($id);
            $this->Manutencaos->deleteOrFail($manutencao);

            return $this->gerarResposta(200, [
               $this->chaveMensagem => 'Manutenção excluída com sucesso.',
            ]);
        }
        catch (RecordNotFoundException) {
            return $this->gerarResposta(400, [
                $this->chaveMensagem => $mensagemNaoEncontrada
            ]);
        }
        catch (PersistenceFailedException $e) {
            return $this->gerarResposta(400, [
                $this->chaveErros => $e->getAttributes()
            ]);
        }
    }
}
