-- DROP DATABASE TADS5;
-- CREATE DATABASE TADS5;
USE TADS5;

SELECT * FROM AUTENTICACAOS;
SELECT * FROM FABRICANTES;
SELECT * FROM FORNECEDORS;
SELECT * FROM MANU_PECAS;
SELECT * FROM MANUTENCAOS;
SELECT * FROM PECAS;
SELECT * FROM SERVICOS;
SELECT * FROM TIPOS;
SELECT * FROM USERS;
SELECT * FROM VEICULOS;

/*
TRUNCATE AUTENTICACAOS;
TRUNCATE FABRICANTES;
TRUNCATE FORNECEDORS;
TRUNCATE MANU_PECAS;
TRUNCATE MANUTENCAOS;
TRUNCATE PECAS;
TRUNCATE SERVICOS;
TRUNCATE TIPOS;
TRUNCATE USERS;
TRUNCATE VEICULOS;
*/

TRUNCATE USERS;
TRUNCATE AUTENTICACAOS;

-- Verificação com token
SELECT TIMESTAMPDIFF(HOUR, CREATED, NOW()) AS DIFERENCA_HORAS
  FROM AUTENTICACAOS
 WHERE AUTENTICACAO = '175fa627af9146037793e0054ca31ad7e5224cc96b5bf625f9243f510c4c93b3'
 LIMIT 1;

SELECT 1
  FROM AUTENTICACAOS
 WHERE AUTENTICACAO = '0242bdb2637228a5f3b863b8373fea010cda0236e38aaff1533ee08a4dfac466'
   AND DATE(NOW()) <= EXPIRACAO
 LIMIT 1;
