-- DROP DATABASE TADS5;
CREATE DATABASE TADS5;
USE TADS5;

SELECT * FROM USERS;
SELECT * FROM AUTENTICACAOS;

UPDATE AUTENTICACAOS
   SET CREATED = DATE_ADD(CREATED, INTERVAL -3 DAY),
   MODIFIED = DATE_ADD(MODIFIED, INTERVAL -3 DAY)
 WHERE ID = 3;

TRUNCATE AUTENTICACAOS;

DELETE FROM USERS WHERE ID >= 1;
-- ALTER TABLE USERS AUTO_INCREMENT = 1;

SELECT TIMESTAMPDIFF(HOUR, CREATED, NOW()) AS DIFERENCA_HORAS
  FROM AUTENTICACAOS
 WHERE AUTENTICACAO = '175fa627af9146037793e0054ca31ad7e5224cc96b5bf625f9243f510c4c93b3'
 LIMIT 1;