-- DROP DATABASE TADS5;
-- CREATE DATABASE TADS5;
USE TADS5;

SELECT * FROM USERS;
SELECT * FROM AUTENTICACAOS;
SELECT * FROM TIPO_SERVICOS;
SELECT * FROM FORNECEDORS;
SELECT * FROM CATEGORIA_PECAS;
SELECT * FROM MARCA_PECAS;
SELECT * FROM PECAS;
SELECT * FROM TIPO_VEICULOS;
SELECT * FROM FABRICANTES;
SELECT * FROM VEICULOS;
SELECT * FROM METRICAS;
SELECT * FROM FREQUENCIA_MANUTENCAOS;
SELECT * FROM MANUTENCAOS;
SELECT * FROM ITEM_MANUTENCAOS;

/*
TRUNCATE AUTENTICACAOS;
TRUNCATE USERS;
TRUNCATE ITEM_MANUTENCAOS;
TRUNCATE MANUTENCAOS;
TRUNCATE VEICULOS;
TRUNCATE FABRICANTES;
TRUNCATE PECAS;
TRUNCATE FORNECEDORS;
TRUNCATE CATEGORIA_PECAS;
TRUNCATE MARCA_PECAS;
TRUNCATE TIPO_SERVICOS;
TRUNCATE TIPO_VEICULOS;
*/

-- ALTER TABLE PECAS AUTO_INCREMENT = 1;

TRUNCATE USERS;
TRUNCATE AUTENTICACAOS;

-- Verificação com token
SELECT TIMESTAMPDIFF(HOUR, CREATED, NOW()) AS DIFERENCA_HORAS
  FROM AUTENTICACAOS
 -- WHERE AUTENTICACAO = '175fa627af9146037793e0054ca31ad7e5224cc96b5bf625f9243f510c4c93b3'
 LIMIT 1;

SELECT 1
  FROM AUTENTICACAOS
 WHERE AUTENTICACAO = '0242bdb2637228a5f3b863b8373fea010cda0236e38aaff1533ee08a4dfac466'
   AND DATE(NOW()) <= EXPIRACAO
 LIMIT 1;
